name: Java CI with Gradle

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application-dev.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-dev.properties
      - run: cat ./src/main/resources/application-dev.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build --debug
        shell: bash