name: Java CI with Gradle

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application-dev.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-dev.properties
      - run: cat ./src/main/resources/application-dev.properties

      - uses: actions/cache@v3  # 반복되는 작업 캐싱하기
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Upload Jacoco Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report # 결과물의 이름
          path: build/reports/jacoco/test/html # upload하고자 하는 파일 또는 디렉토리 경로